services:
  db:
    image: postgres:16-alpine
    container_name: fastapi_crud_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fastapi_db}
      POSTGRES_USER: ${POSTGRES_USER:-fastapi_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fastapi_pass}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
      build: .
      container_name: fastapi_app
      restart: always
      depends_on:
        - db
      env_file:
        - .env
      ports:
        - "8000:8000"

volumes:
  pg_data: